name: Tag
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo name'
        required: true
      release:
        description: 'release id'
        required: true
      apk:
        description: 'apk url'
        required: true
      tag:
        description: 'tag name'
        required: true

run-name: Tag ${{ github.event.inputs.repo }}@${{ github.event.inputs.tag }}

jobs:
  update_tag:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.event.inputs.repo }}
      RELEASE: ${{ github.event.inputs.release }}
      APK: ${{ github.event.inputs.apk }}
      TAG: ${{ github.event.inputs.tag }}
      TAG_TOKEN: ${{ secrets.TAG_TOKEN }}
    steps:
      - run: |
          pip install requests axml GitPython
          python /home/runner/work/modules/.github/workflows/tag.py
